# Generated by Django 3.0.6 on 2020-05-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
