# Generated by Django 3.0.6 on 2020-05-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_like_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
