# Generated by Django 3.0.6 on 2020-06-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_company_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
