# Generated by Django 3.0.6 on 2020-06-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(db_index=True, to='blog.Profile'),
        ),
    ]
